Добавлено ДЗ №4
gilodo/purple-school-js-basic pull request #4
Opened 2024-06-06 11:11 UTC by gilodo

2024-06-07 11:14 UTC, GitEsense requested changes
На доработку функционала

2024-06-07 11:14 UTC, GitEsense commented on 7-converter/app.js
> +alert(convertCurrency(2000, 'EUR', 'USD'));
Вы сделали функцию для одной валюты, а что если я например захочу конвертировать рубли в доллары, потом доллары в евро и евро в рубли, чтобы увидеть "сколько я потеряю на курсах" и обмене?

Если это конвертация рублей в доллары, то и называть стоило бы
convertRubToUsd

Сделайте хотя бы для 3-х валют
RUB, USD, EUR и чтобы одну можно было в другую крутить

2024-06-07 16:08 UTC, gilodo commented on 7-converter/app.js
> +alert(convertCurrency(2000, 'EUR', 'USD'));
Если я не ошибаюсь, это 9 (3^2) комбинаций валют получается. Как мне это реализовать? Через if else else if или switch case? Последний допускает логический оператор && в кейсе (типа case x===a && y===b)?

2024-06-14 09:38 UTC, GitEsense approved these changes

2024-06-14 09:38 UTC, GitEsense commented on 7-converter/app.js
> +console.log(convertCurrency(1000, 'AUD', 'CAD'));
Работать работает, окей, но держать "курсы" и менять каждый раз - это будет как минимум утомительно и сложно 

Чтобы не менять постоянно "коэффициенты", то лучше отталкиваться от одного "основного" курса и к нему приравнивать остальные, вот три разных варианта решения

**Простой SWITCH CASE:**
```js
function converter(sum, currency, targetCurrency) {
    const USD = 90;
    const EUR = 100;

    currency = currency.toUpperCase();
    targetCurrency = targetCurrency.toUpperCase();

    switch (currency) {
        case 'USD':
            switch (targetCurrency) {
                case 'RUB':
                    return sum * USD;
                case 'EUR':
                    return (sum * USD) / EUR;
                default:
                    return null;
            }
        case 'EUR':
            switch (targetCurrency) {
                case 'RUB':
                    return sum * EUR;
                case 'USD':
                    return (sum * EUR) / USD;
                default:
                    return null;
            }
        case 'RUB':
            switch (targetCurrency) {
                case 'USD':
                    return sum / USD;
                case 'EUR':
                    return sum / EUR;
                default:
                    return null;
            }
        default:
            return null;
    }
}

const convertResult = converter(1500, 'rub', 'usd');
console.log(convertResult);
```

**SWITCH CASE с проверками и шаблоном:**
```js
function convertSum(sum, from, to) {
    return ((sum * from) / to).toFixed(2);
}

function getTargetCurrencyIcon(targetCurrency) {
        switch (targetCurrency) {
            case 'RUB':
                return 'руб';
            case 'EUR':
                return '€';
            case 'USD':
                return '$';
            default: return '';
        }
}

function messageTemplate(value, icon){
    return `${value} ${icon}`;
}

function converter(sum, currency, targetCurrency) {
    const ALLOW_CURRENCY_LIST = ['RUB', 'EUR', 'USD'];
    const USD = 91.33;
    const RUB = 1;
    const EUR = 112.33;

    currency = currency.toUpperCase();
    targetCurrency = targetCurrency.toUpperCase();
    const icon = getTargetCurrencyIcon(targetCurrency);

    if (currency === targetCurrency) {
        return messageTemplate(sum, icon);
    }
    if (!ALLOW_CURRENCY_LIST.includes(currency)) {
        console.log('Входящая валюта мне неизвестна');
        return null;
    }
    if (!ALLOW_CURRENCY_LIST.includes(targetCurrency)) {
        console.log('Исходящая валюта мне неизвестна');
        return null;
    }
    
    let value = null;

    switch (currency) {
        case 'USD':
            switch (targetCurrency) {
                case 'RUB': value = convertSum(sum, USD, RUB); break;
                case 'EUR': value = convertSum(sum, USD, EUR); break;
                default: {
                    console.log('Исходящая валюта мне неизвестна');
                    return null;
                }
            }; break;
        case 'RUB':
            switch (targetCurrency) {
                case 'USD': value = convertSum(sum, RUB, USD); break;
                case 'EUR': value = convertSum(sum, RUB, EUR); break;
                default: {
                    console.log('Исходящая валюта мне неизвестна');
                    return null;
                }
            }; break;
        case 'EUR':
            switch (targetCurrency) {
                case 'RUB':
                    value = convertSum(sum, EUR, RUB); break;
                case 'USD':
                    value = convertSum(sum, EUR, USD); break;
                default: {
                    console.log('Исходящая валюта мне неизвестна');
                    return null;
                }
            }; break;
    }

    return messageTemplate(value, icon)
}
```

**Исключительно через массив:**
```js
function convertSum(sum, from, to) {
    return ((sum * from) / to).toFixed(2);
}

function getTargetCurrencyIcon(targetCurrency) {
        switch (targetCurrency) {
            case 'RUB':
                return 'руб';
            case 'EUR':
                return '€';
            case 'USD':
                return '$';
            default: return '';
        }
}

function messageTemplate(value, icon){
    return `${value} ${icon}`;
}

function converter(sum, currency, targetCurrency) {
    const ALLOW_CURRENCY_LIST = [['RUB', 1], ['EUR', 112.33], ['USD', 91.33]];
    const flatList = ALLOW_CURRENCY_LIST.flat();
    currency = currency.toUpperCase();
    targetCurrency = targetCurrency.toUpperCase();

    if (!flatList.includes(currency)) {
        console.log('Входящая валюта мне неизвестна');
        return null;
    }
    if (!flatList.includes(targetCurrency)) {
        console.log('Исходящая валюта мне неизвестна');
        return null;
    }
    const icon = getTargetCurrencyIcon(targetCurrency);
    if (currency === targetCurrency) {
        return messageTemplate(sum, icon);
    }

    const currentIndex = flatList.indexOf(currency) / 2;
    const targetIndex = flatList.indexOf(targetCurrency) / 2;
    const [, currentValue] = ALLOW_CURRENCY_LIST[currentIndex];
    const [, targetValue] = ALLOW_CURRENCY_LIST[targetIndex];
    const result = convertSum(sum, currentValue, targetValue)
    return messageTemplate(result, icon);
}
```

Ну и запросы для "вывода"
```js
console.log(converter(100, 'RUB', 'USD')); // 1.09 $
console.log(converter(100, 'RUB', 'EUR')); // 0.89 €
console.log(converter(1000, 'EUR', 'USD')); // 1229.94 $
console.log(converter(1000, 'USD', 'EUR')); // 813.05 €
console.log(converter(1000, 'EUR', 'RUB')); // 112330.00 руб

console.log(converter(1500, 'EUR', 'RUB'));
console.log(converter(1500, 'USD', 'RUB'));

console.log(converter(10, 'RUB', 'EUR'));
console.log(converter(10, 'USD', 'EUR'));

console.log(converter(10, 'RUB', 'EURU'));
console.log(converter(10, 'USD', 'EUR'));

console.log(converter(10, 'RUB', 'EUR'));
console.log(converter(10, 'USDTY', 'EUR'));
```

2024-06-18 17:52 UTC, merged